langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: codellama
    embedding-model:
      base-url: http://localhost:11434
      model-name: jina/jina-embeddings-v2-small-en